### PR TITLE
Test build on Node 8 LTS

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi @nicolasleger ! Thanks for your contribution !

Did you notice any glitch using Node.js 8?

I believe that it would make life easier for fellow developers if we:
- provide the complete version number in `.travis.yml` and `package.json` (in the engines section)
- provide (and include in this repo) a `package-lock.json` file (automatically generated by npm 5, so that the versions of all dependencies are also listed)

Do you agree? And, if so, would you mind integrating this changes in your PR?

**Comment by nicolasleger** [comment]
Hi,

It depends whether we want to upgrade the node version OR only allow to use it beside the 6.

**Comment by adrienjoly** [comment]
Well, if everything works, let's upgrade to nodejs 8!

**Comment by adrienjoly** [comment]
Next steps:

- [ ] make sure that all tests pass locally, with most recent version of Nodejs 8
- [ ] make sure that switching to that version does not increase memory and/or CPU usage too much

**Comment by adrienjoly** [comment]
Tested locally with Node v8.11.2. => automated tests did pass, and but some of them seem to have become more flaky:

```
12 passing (57.20s)
2 failing

1) upload user profile images click on "Edit profile":
An element could not be located on the page using the given search parameters ("//*[contains(text(), 'Edit profile')]").
running chrome
Error: An element could not be located on the page using the given search parameters ("//*[contains(text(), 'Edit profile')]").
    at click() - index.js:263:37
    at element("//*[contains(text(), 'Edit profile')]") - index.js:263:37
    at url("http://localhost:8080/u/4d94501d1f78ac091dbc9b4d") - index.js:312:3

2) upload user profile images click on "Edit Profile Info":
Cannot read property 'ELEMENT' of null
running chrome
TypeError: Cannot read property 'ELEMENT' of null
    at element("//*[contains(text(), 'Edit Profile Info')]") - index.js:263:37
    at click() - index.js:263:37
    at element("//*[contains(text(), 'Edit profile')]") - index.js:263:37
    at url("http://localhost:8080/u/4d94501d1f78ac091dbc9b4d") - index.js:312:3
```

or

```
38 passing (195.70s)
4 failing

1) bookmarklet - adding from a youtube track user login:
Timeout of 20000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
running chrome
Error: Timeout of 20000ms exceeded. Try to reduce the run time or increase your timeout for testspecs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/Users/adrienjoly/Dev/openwhyd/openwhyd/whydJS/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:238:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

2) upload user profile images go to user profile:
Timeout of 20000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
running chrome
Error: Timeout of 20000ms exceeded. Try to reduce the run time or increase your timeout for testspecs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
    at Timeout.<anonymous> (/Users/adrienjoly/Dev/openwhyd/openwhyd/whydJS/node_modules/wdio-mocha-framework/node_modules/mocha/lib/runnable.js:238:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

3) upload user profile images click on "Edit Profile Info":
An element could not be located on the page using the given search parameters ("./*[contains(text(), 'Edit Profile Info')]").
running chrome
Error: An element could not be located on the page using the given search parameters ("./*[contains(text(), 'Edit Profile Info')]").
    at click() - index.js:263:37
    at element("//*[contains(text(), 'Edit Profile Info')]") - index.js:263:37
    at elements("#loginDiv .username") - getText.js:18:17
    at getText("#loginDiv .username") - index.js:312:3
```

**Comment by adrienjoly** [comment]
For reference, these tests have become flaky also for Node v6. => Behaviour may not be caused by this PR. (as a matter of fact, CI tests passed on this PR!)

**Comment by adrienjoly** [comment]
I found these articles reassuring about use of resources and how to migrate from node 6:
- [Upgrading from Node 6 to Node 8: a real-world performance comparison](https://hackernoon.com/upgrading-from-node-6-to-node-8-a-real-world-performance-comparison-3dfe1fbc92a3)
- [Upgrading Node.js to Version 8 | Joyent](https://www.joyent.com/blog/upgrading-nodejs-to-8)

Did not find anything about memory usage, but whydJS does not seem to be memory-hungry in production anyway, at least compared to mongodb. (~15% vs ~40%)

=> next steps:
- [x] update the PR to match the latest version of master
- [x] make sure that tests pass on travis-ci
- [ ] make sure that tests pass locally
- [ ] make sure that whydJS works with node 8 in production
- [ ] merge the PR
- [ ] release a new minor version of openwhyd

**Pull request merged**
