### PR TITLE
fix: Migrating email Notification Test from WebDriver to Cypress

### LINKED ISSUE #199: Migrate e2e tests from Webdriver to Cypress
WIP: #199

(started to experiment with it during Hackergarten meetup in Paris)

Next steps:
- [x] write a simple first test with Cypress and make it run on GitHub Actions and Circle-CI => PR #197.
- [x] convert an existing e2e/acceptance test suite to Cypress => PR #276
- [x] make sure that cypress tests are run from usual npm scripts (e.g. `npm test` and `npm docker:test`) => PR #298
- [x] migrate other tests
- [x] remove bookmarklet test (and others) from webdriver.io tests

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75362485-migrate-e2e-tests-from-webdriver-to-cypress?utm_campaign=plugin&utm_content=tracker%2F41430033&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41430033&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Salayna**
Closes #199 

## What does this PR do / solve?

Migration of the email notifications tests from WebDriver to Cypress

### CODE REVIEW

**Comment by adrienjoly** [comment]
You're on fire, @Salayna !

Pro tip: before creating a new branch, and in order to prevent conflicts: don't forget to `git pull` from this repo, to your fork's `master` branch.

**Comment by Salayna** [comment]
Trying to do most while I have the ideas and the energy 😉

**Comment by adrienjoly** [comment]
@Salayna I'm unfollowing this PR to reduce the number of github email notifications => please let me know when your PR is ready for review, ok?

**Review by adrienjoly — APPROVED** [review]
Great job, Salayna!

I have two suggestions that you may want to apply before we merge this PR:
1. group the last tests into a separate `context()`, to match the `describe()` block of the old test file.
2. you can now delete `test/specs/email-notifications.tests.js`, as I believe that you finished to migrate all the tests from that file.

**Review by adrienjoly — APPROVED** [review]
Perfect! 👌

**Pull request merged**
