### PR TITLE
replaced old logo and adjusted css styling

### PR DESCRIPTION
**Pull request by namanbiyani**
replaced whyd logo by openwhyd logo and adjusted the css styling

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi! Thank you so much for your pull request!

While testing your changes on my development laptop (using Google Chrome), I saw that the logo is not displayed in its entirety.

screen shot 2018-12-26 at 23 57 48

Do you observe the same behaviour on your end?

**Comment by namanbiyani** [comment]
I am not being able to view my changes in the local account of openwhyd which i made using the steps of install file . please can u help in this a bit

**Comment by adrienjoly** [comment]
Sure! In https://github.com/openwhyd/openwhyd/issues/183#issuecomment-449864405, I had provided you a list of steps. Can you tell me what step did not work as expected?

And, if you were not able to achieve step 1 (setup), can you also tell what command did not work, and what output / response / error message did you get ?

**Comment by namanbiyani** [comment]
I am using Ubuntu .All commands are working but the local server using docker commands is not showing the changes in code which I had made .

**Comment by adrienjoly** [comment]
Oh ok! Can you try

    docker-compose restart web

... And then refresh the http://localhost:8080 page from your web browser?

**Comment by adrienjoly** [comment]
Closing this PR, to be replaced by PR #185.

**Pull request closed without merging**
