### PR TITLE
add - a link to sound nuggets in the stopped playback flash message

### PR DESCRIPTION
**Pull request by SkinyMonkey**

### CODE REVIEW

**Comment by adrienjoly** [comment]
LGTM!

**Comment by SkinyMonkey** [comment]
Did you deploy this? I can't see it :/

**Comment by adrienjoly** [comment]
Not yet, because the travis test does not pass and may need fixing. (and I don't have time to do it now)

**Comment by SkinyMonkey** [comment]
To save you some time:

The before_install command:
    "sudo rm /etc/apt/sources.list.d/mongodb-3.2.list"
Fails because the file does not exists.
Adding the -f to rm, "sudo rm -f /etc/apt/sources.list.d/mongodb-3.2.list"
Would avoid this problem: it would remove the file if it exists, else just continue.

**Comment by adrienjoly** [comment]
It's now in production! Thanks for your help, Adrien!

**Pull request merged**
