### PR TITLE
Algolia brand image updated

### PR DESCRIPTION
**Pull request by znk**
#91

### CODE REVIEW

**Comment by adrienjoly** [comment]
Thank you for your first contribution, @znk !

That being said, the image appears blurry on my screen. Is the image's resolution sufficient for retina screens?

screen shot 2017-09-13 at 14 58 30

**Comment by znk** [comment]
True, Ill put the original back and scale it down with CSS instead.

**Comment by adrienjoly** [comment]
@znk Merged your PR, then replaced png with svg, so that it adapts to whatever screen definition :-)

Thanks for your contribution!

**Comment by znk** [comment]
Thanks. Sorry, was busy at (and still is) job-hunting!

**Comment by adrienjoly** [comment]
No worries! Please tell what kind of opportunity you're looking for! Here or in private if you prefer.

**Pull request merged**
