### PR TITLE
fix(error): 404 redirect when clicking load more on account stream

### LINKED ISSUE #295: 404 when clicking load more on stream
Reported by stefanos:

When trying to press the button “ Load More” in the stream of Openwhyd I get a 404 page

This happens in the browser and in the WHYD app too

### PR DESCRIPTION
**Pull request by compiuta**
Closes #295 .

## What does this PR do / solve?

It looks like the user gets redirected to the 404 page because of a javascript error that involves the template condition inside the script tag. This error prevents the function from running and rendering the correct url for the button.

## Overview of changes

I added individual script tags for each template condition. This removed the error showing up in the console.

## How to test this PR?

@adrienjoly I am having the same issue with data not being able to load when testing locally on my machine so I am not able to test this solution. Let me know if you are able to test this.

Screenshot from 2020-03-20 15-06-47

### CODE REVIEW

**Comment by adrienjoly** [comment]
Good catch! 

Indeed, I recently discovered that the prettier-based auto-formatting that I had added a few months back can cause mustache/hogan templates to break, when they are embedded in JavaScript code, because they are mistakingly taken as JavaScript objects by the formatter.

For instance, resulting to the following invalid template:

```js
{ { # shouldDisplay } }
window.alert('coucou');
{ { / shouldDisplay } } 
```

The best workaround I found so far was to add multiline JS comments around those templating elements.

For instance:

```js
/*{{#shouldDisplay}}*/
window.alert('coucou');
/*{{/shouldDisplay}}*/
```

=> This workaround prevents prettier from trying to re-format these templating elements.

Do you have any other idea on how to prevent this kind of template-breaking formatting from happening again?

**Comment by adrienjoly** [comment]
@compiuta also, about:

> data not being able to load

Did you mean that you can't test locally because you have not enough tracks locally to be able to paginate?

In that case, this scipt may help: https://github.com/openwhyd/openwhyd/blob/master/docs/INSTALL.md#sample-data :-)

**Comment by compiuta** [comment]
@adrienjoly it looks like adding comments around blocks of code is the correct way to prevent prettier formatting https://prettier.io/docs/en/ignore.html

I have added multiline comments around template conditions inside the script tags and the error is no longer sowing.

**Comment by adrienjoly** [comment]
Great job, Compiuta!! 👏 Thanks for doing that!

I'm almost done on the non-regression test. My plan is to merge it to master, to show that the build is broken. And then to merge your PR (that should hopefully fix the build).

**Comment by adrienjoly** [comment]
My PR (with failling non-regression test) is done and merged to `master`.

I'm going to update your PR to the latest version of that branch. => The test should hopefully pass thanks to your fix.

**Comment by adrienjoly** [comment]
image

Thank you, @compiuta, you rock! 💪

**Pull request merged**
