### PR TITLE
added Algolia in search box. closes #92.

### LINKED ISSUE #92: Partnership: Add Algolia logo at bottom of search pop-in
Algolia has been kindly powering Openwhyd's search engine for free. As we're an open source project, the only thing they ask in return is to make their brand more visible.

So far, their logo is only displayed on the search results' page (after pressing ENTER), but not on the search pop-in (before pressing ENTER):

screen shot 2017-09-13 at 14 04 26

We would like to integrate their logo like this:

b

### PR DESCRIPTION
**Pull request by Selbahc**
I have token the liberty to add Algolia logo at the bottom of search pop-in in response of issue #92. Hope everything is OK !

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi @Selbahc !
Congrats and thank you for your 1st contribution! 🎉

I noticed that your PR replaces the whole `common.css` file, probably because your code editor re-indented it fully. (see https://github.com/openwhyd/openwhyd/pull/99/files)

In order to make your changes more clear, would you mind changing just the lines from that file that need to be changed please?
Also, can you explain what is the `whydJSpackage-lock.json` file for?

**Comment by Selbahc** [comment]
I just updated the common.css file so it is more clear, indeed.

The package-lock.json was introduced in npm v5 and is automatically created by npm every time a dependency is installed. It helps preserve the exact same tree (generated by installing dependencies) for subsequent installs. But npm describes it better than me : https://docs.npmjs.com/files/package-lock.json

I can add it to the .gitignore if you prefer !

**Comment by adrienjoly** [comment]
Great job @Selbahc !

Thank you for the info and reference about `package-lock.json`!
Normally, this file should be commited in git. But, as Openwhyd relies on Nodejs v6.11.1 (with is packed with npm v3.10.10), as specified in package.json, I think that it's better not to include it at that stage.

I will now test your changes locally. If everything works as expected, I will merge your PR into `master`, then push it to production.

**Comment by adrienjoly** [comment]
Congrats for your first successful PR, @Selbahc !
It's clean, works great, and UI looks neat! 💪
Feel welcome to contribute again anytime!

**Comment by Selbahc** [comment]
Thanks for your help !
I'm pleased to know everything works great. 
I'll try to find something else that I can do to help 😄

**Pull request merged**
