### PR TITLE
fix(ui): never-ending loading animation on empty search

### LINKED ISSUE #226: never-ending loading animation on empty search
From #213

Also, doing a " " search on openwhyd.org results in a never-ending loading animation + errors in js console + `content.bundle.js.map` user profile trying to be opened! (from server logs)

Capture d’écran 2019-09-24 à 21 24 15

Capture d’écran 2019-09-24 à 21 24 15 copie

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/81164638-never-ending-loading-animation-on-empty-search?utm_campaign=plugin&utm_content=tracker%2F41430033&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41430033&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by compiuta**
Closes #226.

## What does this PR do / solve?

The console javascript error appears because there is a results condition in the file app/templates/searchPage.html.

This condition wraps the tab_tracks element that the file public/js/searchPage.js is looking for. I found 2 front end solutions to this specific issue.

## Overview of changes

First we can wrap the searchPage.js file within the same condition as the html and give some sort of html message stating an invalid search query has been inputed.

Or we can have a condition within the searchPage.js file checking for the element. If the element is not found then the page will redirect to the homepage. This is the technique I found being used by google and amazon when I added an empty query in the url. In this pull request I have used this second solution.

## How to test this PR?

I used the javascript debugger and the console to add a javascript break before entering the condition. After a valid and  empty search there were no errors showing and the page redirected successfully when an empty search was given.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi @compiuta, thanks for your proposal!

I’m currently taking a 10-day vacation and try to relain as disconnected as possible from usual activities, such as reviewing pull requests.

As I’m the only maintainer of this project who has an understanding of the whole codebase, and automated tests dont seem to pass anymore (for some reason), I will forge it a review when I’m back.

If you want to help us save some time, feel free to propose a separate PR to fix the automated tests.

Thank you for your understanding!

Adrien

**Comment by adrienjoly** [comment]
Hey @compiuta, how are you?

I'm sorry it's taking so long for me to review this...

During my holidays, YouTube decided to shut down the API key we've been using for years. Because of that, several users reported that features relying on YouTube (e.g. adding tracks) have been failing. As this is quite a blocking issue impacting many users of Openwhyd, and as I've not found anyone else willing to fix this, I've been investing most of my spare time on these issues since yesterday.

If you want more details about the situation and the fixes being put into place, feel free to have a look to the following tickets:
- https://github.com/openwhyd/openwhyd/issues/262
- https://github.com/openwhyd/openwhyd/issues/266

Thanks for your understanding and patience!

**Comment by compiuta** [comment]
No worries @adrienjoly 

I will take a look and help out if I can.

**Comment by compiuta** [comment]
Alright glad I could help :)

**Comment by adrienjoly** [comment]
@compiuta, if you'd like to contribute again to Openwhyd and are not sure on what, feel free to let me know what kind of tasks you enjoy (and don't enjoy) doing so I can make some recommendations for you.

You can reply here or contact me by email if you prefer. (adrien at openwhyd dot org)

**Comment by compiuta** [comment]
@adrienjoly anything having to do with the front end ui I can gladly help with.

Definitely let me know if there is a specific issue that you would like me to look at.

**Comment by adrienjoly** [comment]
Sure!

Would you rather:
- fix bugs,
- propose and implement changes to some parts of the UI,
- implement a separate UI with the front-end framework of your choice,
- or write end-to-end tests with Cypress ?

**Comment by compiuta** [comment]
I enjoy fixing bugs and let me know if you have a specific issue with some part of the current ui so I can take a look.

**Comment by adrienjoly** [comment]
Hey compuita, I just made a selection of issues that may be relevant for you:

- [Prevent "use desktop/electron app" error message ...when using that app! · Issue #224 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/224)
- [Sometimes hidden logo in navbar on search page · Issue #38 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/38)
- [UX BUG: resizing the pages scrolls to the top · Issue #20 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/20)
- and a potentially trickier one to debug: [Make Deezer tracks work from desktop app · Issue #223 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/223) (i.e. potentially requires debugging both Openwhyd's and PlayemJS' codebases)

Also, in case you'd be interested to discuss higher-level UI/UX improvements:

- [UI: World Whyd Ranking page is slow to display data => user notice should be added · Issue #21 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/21)
- [[UI/Design/Marketing] Refresh the messaging of the landing page · Issue #182 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/182)
- [[UI] improve onboarding and calls to action: add a track, discover people to follow · Issue #163 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/163)

Let me know if you need more info on any of those issues, and/or if you have any question or idea to share.

**Comment by compiuta** [comment]
Sounds good I will take a look and see what I can do :+1:

**Pull request merged**
