### PR TITLE
Wording update

### PR DESCRIPTION
**Pull request by mauricesvay**
This PR addresses #7 

- [x] Renames instances of "Why" and "OpenWhyd" to "Openwhyd"

### CODE REVIEW

**Comment by mauricesvay** [comment]
This PR passes travis tests and should be good for review.

**Comment by Djiit** [comment]
many indentations fixes in the first commit, but otherwise LGTM.

**Comment by mauricesvay** [comment]
Yes, the whole repo has trailing whitespace. The diff is best viewed with `?w=1` on github.

**Comment by adrienjoly** [comment]
Thanks for your contribution, @mauricesvay!
And thanks to @Djiit for the review!

=> I'm going to merge that.

Also, I appreciate that you took that opportunity to remove trailing whitespace. That being said, it would be awesome if you could push different kinds of updates (e.g. whitespace fix VS wording fix) in separate PRs, as proposed in our [contribution guidelines](https://github.com/openwhyd/openwhyd/blob/master/CONTRIBUTING.md#acceptance-criteria-for-pull-requests-pr). I'm happy to read your thoughts, if want to suggest changes in those guidelines. :-)

**Pull request merged**
