### PR TITLE
Makes donation box clearer

### LINKED ISSUE #77: UI: clearer donation invite
- [ ] remove the mention of "$48"
- [ ] add a blue border (1 or 2px) to make the box stand out more

### PR DESCRIPTION
**Pull request by mauricesvay**
capture d ecran 2017-10-08 a 20 21 13

- [x] Adds blue border

This fixes #77

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hey @mauricesvay, long time no see! ;-)

Thanks for your PR, I hope to merge it tomorrow if that's ok for you!

Adrien

**Comment by mauricesvay** [comment]
I figured I should help projects I know and like for Hacktoberfest :)
Let me know if there's anything I should update.

I'll try do dive deeper, but the codebase is a bit hard get into. I'm looking forward to fix more bugs.

**Comment by adrienjoly** [comment]
Your PR is now running in production!
Congrats and thank you for this 1st PR, @mauricesvay! 🎉

**Comment by mauricesvay** [comment]
Awesome!

**Pull request merged**
