### PR TITLE
feat(ci): Add version as tag, when publishing on Docker Hub

### PR DESCRIPTION
**Pull request by adrienjoly**
So far, we've been publishing images to Docker Hub systematically with the `latest` tag. This means that we overwrite the previous version of the image everytime, instead of allowing users to download a specific version of the Openwhyd docker image.

This PR should create a dedicated tag for each version.

## Tests / open questions

Before doing so, can anyone make sure that we're not leaking anythink that we may regret later? (e.g. secrets)

### CODE REVIEW

**Comment by Djiit** [comment]
👋 hi !
I'm not familiar with this particular action but so far the doc is clear (https://github.com/marketplace/actions/publish-docker-action#auto-tag) so we can go with this !

**Comment by Djiit** [comment]
Regarsing secrets, I need to have a deeper look into the code. I'll let you know today when I have time for this.

Cheers

**Comment by adrienjoly** [comment]
Yo @Djiit, thank you so much for the reply, and for the offer to help!

I'm not experienced with publishing docker images publicly (and probably not as experienced as you with Docker), so I'd love to feel more confident about not leaking secrets over there ^^

First things that come to mind, if that's any help about where to look first:
- `env-vars-*` files
- env vars that may have leaked to another files, e.g. generated scripts and/or logs that may have been stored in the image
- same for secret tokens brought by github actions and/or circle-ci, e.g. https://github.com/openwhyd/openwhyd/runs/528204459#step:8:11

Do you think you could have a look?

**Comment by Djiit** [comment]
Hey,

I didnt find any secrets after a quick search. Algolia Key is public anyway so it's ok to share it in the code; but you could remove it to be more strict.

The secrets suggested by your link are stored into the docker container in charge of build your docker (sic) image. No worries !

**Comment by Djiit** [comment]
What you can do is a quick tour of the built image env.

build this image locally, then run sh on it (`docker run -it <imagename> sh`) and try to print the env with `env` : do you see anything strange ? try to list file in the current dir: same question ?

And you will be good to go !

**Comment by adrienjoly** [comment]
Thanks for your reply and suggestions, @Djiit, that's very reassuring and helping for me! 😌

I'll do a quick tour, as you suggested, and hope to merge this before the end of the weekend! 💪

Au plaisir, Julien !

**Comment by adrienjoly** [comment]
I found no secrets while exploring the image using `docker-compose exec web sh`. => Going to merge this PR.

Next step: try to reduce the size of the published images. (#309)

Thanks again for your help, Julien!

**Pull request merged**
